### PR TITLE
Print stacktrace on exception in init context or setup/teardown

### LINKED ISSUE #994: Provide decent stack traces in setup code
When an Error is thrown in setup it'd be nice if an exception was thrown, currently we just get the current function, file and line (which often seems to be wrong?). E.g:

```
$ cat foo.js
import bar from "./bar.js";
export function setup() {
        bar();
};
export default function() {
};
$ cat bar.js 
export default function () {
        baz();
}
function baz() {
        throw new Error("baz");
}
$ docker run -it --rm -v "$PWD:/src" -w /src loadimpact/k6 run foo.js

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /    
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: foo.js

    duration: -,  iterations: 1
         vus: 1, max: 1

ERRO[0000] Engine error                                  error="setup: Error: baz at baz (/src/bar.js:6:8(4))"
ERRO[0000] Engine Error 
```

### PR DESCRIPTION
**Pull request by MStoykov**
also exit with error code 107 for both cases.

fixes #994

### CODE REVIEW

File: cmd/run.go [hunk 1]
```diff
@@ -63,6 +64,7 @@ const (
 	invalidConfigErrorCode       = 104
 	externalAbortErrorCode       = 105
 	cannotStartRESTAPIErrorCode  = 106
+	scriptExceptionErrorCode     = 107
```
Comment (na--) [inline cmd/run.go:67]: This should probably be 108, since we already use 107 in https://github.com/k6io/k6/pull/1920 (we probably should also move these to the `consts` package eventually)

File: js/initcontext_test.go [hunk 2]
```diff
@@ -131,7 +131,7 @@ func TestInitContextRequire(t *testing.T) {
 			fs := afero.NewMemMapFs()
 			assert.NoError(t, afero.WriteFile(fs, "/file.js", []byte(`throw new Error("aaaa")`), 0o755))
 			_, err := getSimpleBundle(t, "/script.js", `import "/file.js"; export default function() {}`, fs)
-			assert.EqualError(t, err, "Error: aaaa at file:///file.js:2:7(4)")
+			assert.EqualError(t, err, "Error: aaaa\n\tat file:///file.js:2:7(4)\n\tat reflect.methodValueCall (native)\n\tat file:///script.js:1:117(14)\n")
```
Comment (na--) [inline js/initcontext_test.go:134]: This `reflect.methodValueCall (native)` is not a great improvement to not having a stack trace at all :sweat_smile: Can you please also add a test that has a stacktrace consisting of purely JS functions?

**Review by na-- — COMMENTED** [review]
Mostly LGTM, though I'd like to play around with it a bit before it's merged. 

Should we try to release this in k6 v0.32.0?

File: lib/types/types.go [hunk 3]
```diff
@@ -280,3 +280,10 @@ func GetDurationValue(v interface{}) (time.Duration, error) {
 		return time.Duration(n) * time.Millisecond, nil
 	}
 }
+
+// ScriptException is an interface to be used to represent and error as a result of script exception.
```
Comment (imiric) [inline lib/types/types.go:284]:
```suggestion
// ScriptException is an interface used to represent an error as a result of a script exception.
```

File: js/initcontext_test.go (hunk 2 above)
Comment (MStoykov) [reply js/initcontext_test.go:134]: This is technically `script.js`-> `reflect.methodValueCall`->`file.js`

File: cmd/run.go (hunk 1 above)
Comment (MStoykov) [reply cmd/run.go:67]: I don't think it really matters who gets `107` and who gets `108`. 

Whoever is merged second will have a conflict and will need to resolve it.

Given that IMO this is more likely to be merged now I prefer to no add a "hole" in the error codes ;)

**Comment by MStoykov** [comment]
I specifically didn't add it as v0.32.0, because I also wonder, it's pretty small and the worst case is ... somehow it breaks some stacktrace case?!? 

On the other hand,today is the cut off date so ;)

File: cmd/run.go (hunk 1 above)
Comment (na--) [reply cmd/run.go:67]: fair enough :+1:

**Review by imiric — COMMENTED** [review]
LGTM, and works fine from what I could test.

Agree with Ned that a more complex test is needed. Maybe just replicating the example from #994 with `setup()` and `teardown()`?

:+1: for releasing this in v0.32.0.

**Review by imiric — APPROVED** [review]

**Review by na-- — APPROVED** [review]
